services:
  dev:
    build: .
    image: class-autocast:v1
    # We do not want to recreate the container or have multiple instances of it running ever
    container_name: class-autocast
    volumes:
      # Mount SSH Keys as readonly
      - ~/.ssh:/root/.ssh:ro
      # Mount gitconfig
      - ~/.gitconfig:/root/.gitconfig:ro
      # Mount working folder
      - ../:/home/workspace
    # The following commands ensure that the container stays active
    entrypoint: bash
    stdin_open: true
    tty: true