concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

name: Merge Request Checks
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  actions: write
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: 🔬 Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
      - run: npm install -g yarn
      - run: corepack enable
      - run: yarn install
      - run: yarn prettier-check
      - run: yarn lint-check
